class Runner{
	public static void main(String[] args){
		// Laptop
        Laptop.updateSoftware();
        Laptop.enableBluetooth();
        Laptop.adjustBrightness();
        Laptop.checkStorage();
        Laptop.powerOff();
        System.out.println("====================================================================================================================="); 
        // Lollipop
        Lollipop.share();
        Lollipop.changeFlavor();
        Lollipop.dissolve();
        Lollipop.breakHalf();
        Lollipop.checkExpiry();
        System.out.println("=====================================================================================================================");
		//IplCup
		IplCup.organizeOpeningCeremony();
		IplCup.promoteTeams();
		IplCup.conductAuction();
		IplCup.monitorFairPlay();
		IplCup.finalizeVenues();
		System.out.println("=====================================================================================================================");
		//Globe
        Globe.displayLatLong();
        Globe.highlightPoles();
        Globe.markCapitals();
        Globe.educateGeography();
        Globe.spinFast();
		System.out.println("=====================================================================================================================");
		//Supra
        Supra.boostTurbo();
        Supra.checkSpeed();
        Supra.playMusic();
        Supra.enableSportMode();
        Supra.parkCar();
		System.out.println("=====================================================================================================================");
		//Icecream
        Icecream.changeFlavor();
        Icecream.makeSundae();
        Icecream.pack();
        Icecream.eat();
        Icecream.enjoy();
		System.out.println("=====================================================================================================================");
		//Atom
        Atom.showNeutrons();
        Atom.showElectrons();
        Atom.ionize();
        Atom.emitRadiation();
        Atom.combineElements();
		System.out.println("=====================================================================================================================");
		//MNCCompany
        MNCCompany.expandBusiness();
        MNCCompany.acquireCompany();
        MNCCompany.mergeCompanies();
        MNCCompany.paySalaries();
        MNCCompany.conductTraining();
		System.out.println("=====================================================================================================================");
		//ICC
        ICC.approveNewTeams();
        ICC.overseeUmpires();
        ICC.handleSponsorships();
        ICC.reviewPlayerConduct();
        ICC.scheduleMatches();
		System.out.println("=====================================================================================================================");
		//RCB
        RCB.buyPlayers();
        RCB.sellPlayers();
        RCB.releaseJersey();
        RCB.hireCoach();
        RCB.manageSponsors();
}
}