package com.xworkz.overrideToString.runner;

import com.xworkz.overrideToString.internal.*;

public class Runner {
    public static void main(String[] args) {
        ActionFigure figure1 = new ActionFigure("Marvel", "Iron Man", 6);
        System.out.println(figure1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(figure1));
        System.out.println("Default Hash Code: " + figure1.hashCode());
        System.out.println("====================================================================");
        ActionFigure figure2 = new ActionFigure("Marvel", "Iron Man", 6);
        System.out.println(figure2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(figure2));
        System.out.println("Default Hash Code: " + figure2.hashCode());
        System.out.println("Is Two instances same ? : "+figure1.equals(figure2));
        System.out.println("====================================================================");
        AirFryer airFryer1 = new AirFryer("Ninja", "AF101", 4);
        System.out.println(airFryer1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(airFryer1));
        System.out.println("Default Hash Code: " + airFryer1.hashCode());
        System.out.println("====================================================================");
        AirFryer airFryer2 = new AirFryer("Instant", "Vortex", 6);
        System.out.println(airFryer2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(airFryer2));
        System.out.println("Default Hash Code: " + airFryer2.hashCode());
        System.out.println("Is Two instances same ? : "+airFryer1.equals(airFryer2));
        System.out.println("====================================================================");
        AirPurifier airPurifier1 = new AirPurifier("Dyson", "Pure Cool", 3);
        System.out.println(airPurifier1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(airPurifier1));
        System.out.println("Default Hash Code: " + airPurifier1.hashCode());
        System.out.println("====================================================================");
        AirPurifier airPurifier2 = new AirPurifier("Dyson", "Pure Cool", 3);
        System.out.println(airPurifier2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(airPurifier2));
        System.out.println("Default Hash Code: " + airPurifier2.hashCode());
        System.out.println("Is Two instances same ? : "+airPurifier1.equals(airPurifier2));
        System.out.println("====================================================================");
        Backpack backpack1 = new Backpack("North Face", "Borealis", 28);
        System.out.println(backpack1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(backpack1));
        System.out.println("Default Hash Code: " + backpack1.hashCode());
        System.out.println("====================================================================");
        Backpack backpack2 = new Backpack("JanSport", "SuperBreak", 25);
        System.out.println(backpack2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(backpack2));
        System.out.println("Default Hash Code: " + backpack2.hashCode());
        System.out.println("Is Two instances same ? : "+backpack1.equals(backpack2));
        System.out.println("====================================================================");
        Basketball basketball1 = new Basketball("Spalding", "NBA Official", 29.5);
        System.out.println(basketball1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(basketball1));
        System.out.println("Default Hash Code: " + basketball1.hashCode());
        System.out.println("====================================================================");
        Basketball basketball2 = new Basketball("Wilson", "Evolution", 28.5);
        System.out.println(basketball2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(basketball2));
        System.out.println("Default Hash Code: " + basketball2.hashCode());
        System.out.println("Is Two instances same ? : "+basketball1.equals(basketball2));
        System.out.println("====================================================================");
        BaseballBat baseballBat1 = new BaseballBat("Easton", "Ghost", 32);
        System.out.println(baseballBat1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(baseballBat1));
        System.out.println("Default Hash Code: " + baseballBat1.hashCode());
        System.out.println("====================================================================");
        BaseballBat baseballBat2 = new BaseballBat("Easton", "Ghost", 32);
        System.out.println(baseballBat2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(baseballBat2));
        System.out.println("Default Hash Code: " + baseballBat2.hashCode());
        System.out.println("Is Two instances same ? : "+baseballBat1.equals(baseballBat2));
        System.out.println("====================================================================");
        Binoculars binoculars1 = new Binoculars("Nikon", "Prostaff", 10);
        System.out.println(binoculars1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(binoculars1));
        System.out.println("Default Hash Code: " + binoculars1.hashCode());
        System.out.println("====================================================================");
        Binoculars binoculars2 = new Binoculars("Bushnell", "Legend", 8);
        System.out.println(binoculars2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(binoculars2));
        System.out.println("Default Hash Code: " + binoculars2.hashCode());
        System.out.println("Is Two instances same ? : "+binoculars1.equals(binoculars2));
        System.out.println("====================================================================");
        Blender blender1 = new Blender("Vitamix", "5200", 64);
        System.out.println(blender1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(blender1));
        System.out.println("Default Hash Code: " + blender1.hashCode());
        System.out.println("====================================================================");
        Blender blender2 = new Blender("Ninja", "Professional", 72);
        System.out.println(blender2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(blender2));
        System.out.println("Default Hash Code: " + blender2.hashCode());
        System.out.println("Is Two instances same ? : "+blender1.equals(blender2));
        System.out.println("====================================================================");
        BloodPressureMonitor bpMonitor1 = new BloodPressureMonitor("Omron", "Silver", "Upper Arm");
        System.out.println(bpMonitor1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bpMonitor1));
        System.out.println("Default Hash Code: " + bpMonitor1.hashCode());
        System.out.println("====================================================================");
        BloodPressureMonitor bpMonitor2 = new BloodPressureMonitor("Withings", "BPM Core", "Wrist");
        System.out.println(bpMonitor2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bpMonitor2));
        System.out.println("Default Hash Code: " + bpMonitor2.hashCode());
        System.out.println("Is Two instances same ? : "+bpMonitor1.equals(bpMonitor2));
        System.out.println("====================================================================");
        BoardGame boardGame1 = new BoardGame("Catan", "Strategy", 4);
        System.out.println(boardGame1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(boardGame1));
        System.out.println("Default Hash Code: " + boardGame1.hashCode());
        System.out.println("====================================================================");
        BoardGame boardGame2 = new BoardGame("Catan", "Strategy", 4);
        System.out.println(boardGame2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(boardGame2));
        System.out.println("Default Hash Code: " + boardGame2.hashCode());
        System.out.println("Is Two instances same ? : "+boardGame1.equals(boardGame2));
        System.out.println("====================================================================");
        Briefcase briefcase1 = new Briefcase("Tumi", "Alpha", "Leather");
        System.out.println(briefcase1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(briefcase1));
        System.out.println("Default Hash Code: " + briefcase1.hashCode());
        System.out.println("====================================================================");
        Briefcase briefcase2 = new Briefcase("Samsonite", "Executive", "Nylon");
        System.out.println(briefcase2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(briefcase2));
        System.out.println("Default Hash Code: " + briefcase2.hashCode());
        System.out.println("Is Two instances same ? : "+briefcase1.equals(briefcase2));
        System.out.println("====================================================================");
        Calculator calculator1 = new Calculator("Texas Instruments", "TI-84", "Scientific");
        System.out.println(calculator1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(calculator1));
        System.out.println("Default Hash Code: " + calculator1.hashCode());
        System.out.println("====================================================================");
        Calculator calculator2 = new Calculator("Casio", "FX-991EX", "Engineering");
        System.out.println(calculator2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(calculator2));
        System.out.println("Default Hash Code: " + calculator2.hashCode());
        System.out.println("Is Two instances same ? : "+calculator1.equals(calculator2));
        System.out.println("====================================================================");
        Camera camera1 = new Camera("Sony", "A7IV", 33);
        System.out.println(camera1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(camera1));
        System.out.println("Default Hash Code: " + camera1.hashCode());
        System.out.println("====================================================================");
        Camera camera2 = new Camera("Sony", "A7IV", 33);
        System.out.println(camera2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(camera2));
        System.out.println("Default Hash Code: " + camera2.hashCode());
        System.out.println("Is Two instances same ? : "+camera1.equals(camera2));
        System.out.println("====================================================================");
        CampingStove stove1 = new CampingStove("Jetboil", "Flash", 1);
        System.out.println(stove1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(stove1));
        System.out.println("Default Hash Code: " + stove1.hashCode());
        System.out.println("====================================================================");
        CampingStove stove2 = new CampingStove("MSR", "PocketRocket", 2);
        System.out.println(stove2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(stove2));
        System.out.println("Default Hash Code: " + stove2.hashCode());
        System.out.println("Is Two instances same ? : " + stove1.equals(stove2));
        System.out.println("====================================================================");
        CoffeeMaker coffeeMaker1 = new CoffeeMaker("Keurig", "K-Elite", 12);
        System.out.println(coffeeMaker1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(coffeeMaker1));
        System.out.println("Default Hash Code: " + coffeeMaker1.hashCode());
        System.out.println("====================================================================");
        CoffeeMaker coffeeMaker2 = new CoffeeMaker("Breville", "Barista Express", 15);
        System.out.println(coffeeMaker2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(coffeeMaker2));
        System.out.println("Default Hash Code: " + coffeeMaker2.hashCode());
        System.out.println("Is Two instances same ? : " + coffeeMaker1.equals(coffeeMaker2));
        System.out.println("====================================================================");
        Cooler cooler1 = new Cooler("Yeti", "Tundra", 65);
        System.out.println(cooler1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(cooler1));
        System.out.println("Default Hash Code: " + cooler1.hashCode());
        System.out.println("====================================================================");
        Cooler cooler2 = new Cooler("Coleman", "Steel Belted", 50);
        System.out.println(cooler2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(cooler2));
        System.out.println("Default Hash Code: " + cooler2.hashCode());
        System.out.println("Is Two instances same ? : " + cooler1.equals(cooler2));
        System.out.println("====================================================================");
        ComputerMouse mouse1 = new ComputerMouse("Razer", "DeathAdder", 20000);
        System.out.println(mouse1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(mouse1));
        System.out.println("Default Hash Code: " + mouse1.hashCode());
        System.out.println("====================================================================");
        ComputerMouse mouse2 = new ComputerMouse("Logitech", "MX Master", 4000);
        System.out.println(mouse2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(mouse2));
        System.out.println("Default Hash Code: " + mouse2.hashCode());
        System.out.println("Is Two instances same ? : " + mouse1.equals(mouse2));
        System.out.println("====================================================================");
        CurlingIron curlingIron1 = new CurlingIron("BaByliss", "PRO Nano", 1.25);
        System.out.println(curlingIron1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(curlingIron1));
        System.out.println("Default Hash Code: " + curlingIron1.hashCode());
        System.out.println("====================================================================");
        CurlingIron curlingIron2 = new CurlingIron("Conair", "InfinitiPro", 1.0);
        System.out.println(curlingIron2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(curlingIron2));
        System.out.println("Default Hash Code: " + curlingIron2.hashCode());
        System.out.println("Is Two instances same ? : " + curlingIron1.equals(curlingIron2));
        System.out.println("====================================================================");
        DeskLamp lamp1 = new DeskLamp("TaoTronics", "LED Desk Lamp", "Adjustable");
        System.out.println(lamp1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(lamp1));
        System.out.println("Default Hash Code: " + lamp1.hashCode());
        System.out.println("====================================================================");
        DeskLamp lamp2 = new DeskLamp("BenQ", "e-Reading", "Dimmable");
        System.out.println(lamp2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(lamp2));
        System.out.println("Default Hash Code: " + lamp2.hashCode());
        System.out.println("Is Two instances same ? : " + lamp1.equals(lamp2));
        System.out.println("====================================================================");
        Drone drone1 = new Drone("DJI", "Mavic 3", 4);
        System.out.println(drone1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(drone1));
        System.out.println("Default Hash Code: " + drone1.hashCode());
        System.out.println("====================================================================");
        Drone drone2 = new Drone("Autel", "EVO Lite+", 6);
        System.out.println(drone2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(drone2));
        System.out.println("Default Hash Code: " + drone2.hashCode());
        System.out.println("drone1 equals drone2: " + drone1.equals(drone2));
        System.out.println("====================================================================");
        DroneRacingSet racingDrone1 = new DroneRacingSet("DJI", "FPV", 87);
        System.out.println(racingDrone1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(racingDrone1));
        System.out.println("Default Hash Code: " + racingDrone1.hashCode());
        System.out.println("====================================================================");
        DroneRacingSet racingDrone2 = new DroneRacingSet("BetaFPV", "Cetus Pro", 75);
        System.out.println(racingDrone2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(racingDrone2));
        System.out.println("Default Hash Code: " + racingDrone2.hashCode());
        System.out.println("racingDrone1 equals racingDrone2: " + racingDrone1.equals(racingDrone2));
        System.out.println("====================================================================");
        Dumbbell dumbbell1 = new Dumbbell("Bowflex", "SelectTech", 50);
        System.out.println(dumbbell1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(dumbbell1));
        System.out.println("Default Hash Code: " + dumbbell1.hashCode());
        System.out.println("====================================================================");
        Dumbbell dumbbell2 = new Dumbbell("CAP", "Enamel Coated", 40);
        System.out.println(dumbbell2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(dumbbell2));
        System.out.println("Default Hash Code: " + dumbbell2.hashCode());
        System.out.println("dumbbell1 equals dumbbell2: " + dumbbell1.equals(dumbbell2));
        System.out.println("====================================================================");
        DumbbellSet dumbbellSet1 = new DumbbellSet("Bowflex", "SelectTech", 52.5);
        System.out.println(dumbbellSet1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(dumbbellSet1));
        System.out.println("Default Hash Code: " + dumbbellSet1.hashCode());
        System.out.println("====================================================================");
        DumbbellSet dumbbellSet2 = new DumbbellSet("PowerBlock", "Elite", 50);
        System.out.println(dumbbellSet2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(dumbbellSet2));
        System.out.println("Default Hash Code: " + dumbbellSet2.hashCode());
        System.out.println("dumbbellSet1 equals dumbbellSet2: " + dumbbellSet1.equals(dumbbellSet2));
        System.out.println("====================================================================");
        ElectricBike eBike1 = new ElectricBike("Rad Power", "RadRover", 750);
        System.out.println(eBike1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(eBike1));
        System.out.println("Default Hash Code: " + eBike1.hashCode());
        System.out.println("====================================================================");
        ElectricBike eBike2 = new ElectricBike("Trek", "Powerfly", 500);
        System.out.println(eBike2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(eBike2));
        System.out.println("Default Hash Code: " + eBike2.hashCode());
        System.out.println("eBike1 equals eBike2: " + eBike1.equals(eBike2));
        System.out.println("====================================================================");
        ElectricKettle kettle1 = new ElectricKettle("Breville", "BKE820", 1.7);
        System.out.println(kettle1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kettle1));
        System.out.println("Default Hash Code: " + kettle1.hashCode());
        System.out.println("====================================================================");
        ElectricKettle kettle2 = new ElectricKettle("Cuisinart", "PerfecTemp", 1.5);
        System.out.println(kettle2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kettle2));
        System.out.println("Default Hash Code: " + kettle2.hashCode());
        System.out.println("kettle1 equals kettle2: " + kettle1.equals(kettle2));
        System.out.println("====================================================================");
        ElectricScooter scooter1 = new ElectricScooter("Xiaomi", "Mi 365", 18.6);
        System.out.println(scooter1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(scooter1));
        System.out.println("Default Hash Code: " + scooter1.hashCode());
        System.out.println("====================================================================");
        ElectricScooter scooter2 = new ElectricScooter("Segway", "Ninebot MAX", 30);
        System.out.println(scooter2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(scooter2));
        System.out.println("Default Hash Code: " + scooter2.hashCode());
        System.out.println("scooter1 equals scooter2: " + scooter1.equals(scooter2));
        System.out.println("====================================================================");
        ElectricShaver shaver1 = new ElectricShaver("Braun", "Series 9", "Foil");
        System.out.println(shaver1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(shaver1));
        System.out.println("Default Hash Code: " + shaver1.hashCode());
        System.out.println("====================================================================");
        ElectricShaver shaver2 = new ElectricShaver("Philips", "Norelco", "Rotary");
        System.out.println(shaver2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(shaver2));
        System.out.println("Default Hash Code: " + shaver2.hashCode());
        System.out.println("shaver1 equals shaver2: " + shaver1.equals(shaver2));
        System.out.println("====================================================================");
        Elliptical elliptical1 = new Elliptical("ProForm", "Carbon E7", 20);
        System.out.println(elliptical1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(elliptical1));
        System.out.println("Default Hash Code: " + elliptical1.hashCode());
        System.out.println("====================================================================");
        Elliptical elliptical2 = new Elliptical("NordicTrack", "FS7i", 22);
        System.out.println(elliptical2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(elliptical2));
        System.out.println("Default Hash Code: " + elliptical2.hashCode());
        System.out.println("elliptical1 equals elliptical2: " + elliptical1.equals(elliptical2));
        System.out.println("====================================================================");
        ExerciseBike exerciseBike1 = new ExerciseBike("Peloton", "Bike+", 21.5);
        System.out.println(exerciseBike1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(exerciseBike1));
        System.out.println("Default Hash Code: " + exerciseBike1.hashCode());
        System.out.println("====================================================================");
        ExerciseBike exerciseBike2 = new ExerciseBike("Echelon", "EX-5", 24);
        System.out.println(exerciseBike2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(exerciseBike2));
        System.out.println("Default Hash Code: " + exerciseBike2.hashCode());
        System.out.println("exerciseBike1 equals exerciseBike2: " + exerciseBike1.equals(exerciseBike2));
        System.out.println("====================================================================");
        ExternalHDD hdd1 = new ExternalHDD("WD", "My Passport", 2);
        System.out.println(hdd1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hdd1));
        System.out.println("Default Hash Code: " + hdd1.hashCode());
        System.out.println("====================================================================");
        ExternalHDD hdd2 = new ExternalHDD("Seagate", "Backup Plus", 4);
        System.out.println(hdd2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hdd2));
        System.out.println("Default Hash Code: " + hdd2.hashCode());
        System.out.println("hdd1 equals hdd2: " + hdd1.equals(hdd2));
        System.out.println("====================================================================");
        FishingReel reel1 = new FishingReel("Shimano", "Stradic", 3000);
        System.out.println(reel1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(reel1));
        System.out.println("Default Hash Code: " + reel1.hashCode());
        System.out.println("====================================================================");
        FishingReel reel2 = new FishingReel("Daiwa", "BG", 4000);
        System.out.println(reel2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(reel2));
        System.out.println("Default Hash Code: " + reel2.hashCode());
        System.out.println("Is Two instances same ? : "+reel1.equals(reel2));
        System.out.println("====================================================================");

        FishingRod fishingRod1 = new FishingRod("Shimano", "Stella", 7);
        System.out.println(fishingRod1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(fishingRod1));
        System.out.println("Default Hash Code: " + fishingRod1.hashCode());
        System.out.println("====================================================================");
        FishingRod fishingRod2 = new FishingRod("St. Croix", "Premier", 6);
        System.out.println(fishingRod2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(fishingRod2));
        System.out.println("Default Hash Code: " + fishingRod2.hashCode());
        System.out.println("Is Two instances same ? : "+fishingRod1.equals(fishingRod2));
        System.out.println("====================================================================");

        FlashDrive flashDrive1 = new FlashDrive("SanDisk", "Ultra Fit", 128);
        System.out.println(flashDrive1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(flashDrive1));
        System.out.println("Default Hash Code: " + flashDrive1.hashCode());
        System.out.println("====================================================================");
        FlashDrive flashDrive2 = new FlashDrive("Samsung", "BAR Plus", 256);
        System.out.println(flashDrive2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(flashDrive2));
        System.out.println("Default Hash Code: " + flashDrive2.hashCode());
        System.out.println("Is Two instances same ? : "+flashDrive1.equals(flashDrive2));
        System.out.println("====================================================================");

        FoamRoller roller1 = new FoamRoller("TriggerPoint", "Grid", "High Density");
        System.out.println(roller1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(roller1));
        System.out.println("Default Hash Code: " + roller1.hashCode());
        System.out.println("====================================================================");
        FoamRoller roller2 = new FoamRoller("RumbleRoller", "Xtra Firm", "Bumpy");
        System.out.println(roller2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(roller2));
        System.out.println("Default Hash Code: " + roller2.hashCode());
        System.out.println("Is Two instances same ? : "+roller1.equals(roller2));
        System.out.println("====================================================================");

        FoodProcessor foodProcessor1 = new FoodProcessor("Cuisinart", "DFP-14BCNY", 14);
        System.out.println(foodProcessor1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(foodProcessor1));
        System.out.println("Default Hash Code: " + foodProcessor1.hashCode());
        System.out.println("====================================================================");
        FoodProcessor foodProcessor2 = new FoodProcessor("Breville", "Sous Chef", 16);
        System.out.println(foodProcessor2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(foodProcessor2));
        System.out.println("Default Hash Code: " + foodProcessor2.hashCode());
        System.out.println("Is Two instances same ? : "+foodProcessor1.equals(foodProcessor2));
        System.out.println("====================================================================");

        FountainPen pen1 = new FountainPen("Montblanc", "Meisterstück", "Gold");
        System.out.println(pen1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(pen1));
        System.out.println("Default Hash Code: " + pen1.hashCode());
        System.out.println("====================================================================");
        FountainPen pen2 = new FountainPen("Pilot", "Custom 74", "14K Gold");
        System.out.println(pen2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(pen2));
        System.out.println("Default Hash Code: " + pen2.hashCode());
        System.out.println("Is Two instances same ? : "+pen1.equals(pen2));
        System.out.println("====================================================================");

        GamingConsole console1 = new GamingConsole("Sony", "PlayStation 5", "Digital");
        System.out.println(console1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(console1));
        System.out.println("Default Hash Code: " + console1.hashCode());
        System.out.println("====================================================================");
        GamingConsole console2 = new GamingConsole("Microsoft", "Xbox Series X", "Disc");
        System.out.println(console2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(console2));
        System.out.println("Default Hash Code: " + console2.hashCode());
        System.out.println("Is Two instances same ? : "+console1.equals(console2));
        System.out.println("====================================================================");

        GamingController controller1 = new GamingController("Microsoft", "Xbox Elite", "Wireless");
        System.out.println(controller1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(controller1));
        System.out.println("Default Hash Code: " + controller1.hashCode());
        System.out.println("====================================================================");
        GamingController controller2 = new GamingController("Sony", "DualSense", "Bluetooth");
        System.out.println(controller2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(controller2));
        System.out.println("Default Hash Code: " + controller2.hashCode());
        System.out.println("Is Two instances same ? : "+controller1.equals(controller2));
        System.out.println("====================================================================");

        GolfClub golfClub1 = new GolfClub("Callaway", "Mavrik", "Driver");
        System.out.println(golfClub1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(golfClub1));
        System.out.println("Default Hash Code: " + golfClub1.hashCode());
        System.out.println("====================================================================");
        GolfClub golfClub2 = new GolfClub("TaylorMade", "SIM2", "3-Wood");
        System.out.println(golfClub2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(golfClub2));
        System.out.println("Default Hash Code: " + golfClub2.hashCode());
        System.out.println("Is Two instances same ? : "+golfClub1.equals(golfClub2));
        System.out.println("====================================================================");

        GraphicsTablet tablet1 = new GraphicsTablet("Wacom", "Intuos", "Medium");
        System.out.println(tablet1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tablet1));
        System.out.println("Default Hash Code: " + tablet1.hashCode());
        System.out.println("====================================================================");
        GraphicsTablet tablet2 = new GraphicsTablet("Huion", "Kamvas", "Large");
        System.out.println(tablet2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tablet2));
        System.out.println("Default Hash Code: " + tablet2.hashCode());
        System.out.println("Is Two instances same ? : "+tablet1.equals(tablet2));
        System.out.println("====================================================================");

        Guitar guitar1 = new Guitar("Fender", "Stratocaster", 6);
        System.out.println(guitar1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(guitar1));
        System.out.println("Default Hash Code: " + guitar1.hashCode());
        System.out.println("====================================================================");
        Guitar guitar2 = new Guitar("Gibson", "Les Paul", 6);
        System.out.println(guitar2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(guitar2));
        System.out.println("Default Hash Code: " + guitar2.hashCode());
        System.out.println("Is Two instances same ? : "+guitar1.equals(guitar2));
        System.out.println("====================================================================");

        HairDryer hairDryer1 = new HairDryer("Dyson", "Supersonic", 1875);
        System.out.println(hairDryer1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hairDryer1));
        System.out.println("Default Hash Code: " + hairDryer1.hashCode());
        System.out.println("====================================================================");
        HairDryer hairDryer2 = new HairDryer("Revlon", "One Step", 1100);
        System.out.println(hairDryer2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hairDryer2));
        System.out.println("Default Hash Code: " + hairDryer2.hashCode());
        System.out.println("Is Two instances same ? : "+hairDryer1.equals(hairDryer2));
        System.out.println("====================================================================");

        Hammock hammock1 = new Hammock("ENO", "DoubleNest", 400);
        System.out.println(hammock1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hammock1));
        System.out.println("Default Hash Code: " + hammock1.hashCode());
        System.out.println("====================================================================");
        Hammock hammock2 = new Hammock("Kammok", "Roo", 500);
        System.out.println(hammock2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hammock2));
        System.out.println("Default Hash Code: " + hammock2.hashCode());
        System.out.println("Is Two instances same ? : "+hammock1.equals(hammock2));
        System.out.println("====================================================================");

        Headphones headphones1 = new Headphones("Sony", "WH-1000XM5", true);
        System.out.println(headphones1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(headphones1));
        System.out.println("Default Hash Code: " + headphones1.hashCode());
        System.out.println("====================================================================");
        Headphones headphones2 = new Headphones("Bose", "QuietComfort 45", true);
        System.out.println(headphones2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(headphones2));
        System.out.println("Default Hash Code: " + headphones2.hashCode());
        System.out.println("Is Two instances same ? : "+headphones1.equals(headphones2));
        System.out.println("====================================================================");

        Humidifier humidifier1 = new Humidifier("Honeywell", "HEV685", 1.5);
        System.out.println(humidifier1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(humidifier1));
        System.out.println("Default Hash Code: " + humidifier1.hashCode());
        System.out.println("====================================================================");
        Humidifier humidifier2 = new Humidifier("Levoit", "LV600HH", 2.5);
        System.out.println(humidifier2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(humidifier2));
        System.out.println("Default Hash Code: " + humidifier2.hashCode());
        System.out.println("Is Two instances same ? : "+humidifier1.equals(humidifier2));
        System.out.println("====================================================================");

        JumpRope jumpRope1 = new JumpRope("Crossrope", "Get Lean", "Weighted");
        System.out.println(jumpRope1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(jumpRope1));
        System.out.println("Default Hash Code: " + jumpRope1.hashCode());
        System.out.println("====================================================================");
        JumpRope jumpRope2 = new JumpRope("RX Smart Gear", "Pro", "Beaded");
        System.out.println(jumpRope2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(jumpRope2));
        System.out.println("Default Hash Code: " + jumpRope2.hashCode());
        System.out.println("Is Two instances same ? : "+jumpRope1.equals(jumpRope2));
        System.out.println("====================================================================");

        Juicer juicer1 = new Juicer("Omega", "NC900HDC", "Cold Press");
        System.out.println(juicer1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(juicer1));
        System.out.println("Default Hash Code: " + juicer1.hashCode());
        System.out.println("====================================================================");
        Juicer juicer2 = new Juicer("Breville", "Juice Fountain", "Centrifugal");
        System.out.println(juicer2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(juicer2));
        System.out.println("Default Hash Code: " + juicer2.hashCode());
        System.out.println("Is Two instances same ? : "+juicer1.equals(juicer2));
        System.out.println("====================================================================");

        Kettlebell kettlebell1 = new Kettlebell("CAP", "Enamel Coated", 35);
        System.out.println(kettlebell1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kettlebell1));
        System.out.println("Default Hash Code: " + kettlebell1.hashCode());
        System.out.println("====================================================================");
        Kettlebell kettlebell2 = new Kettlebell("Rogue", "E-Coated", 53);
        System.out.println(kettlebell2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kettlebell2));
        System.out.println("Default Hash Code: " + kettlebell2.hashCode());
        System.out.println("Is Two instances same ? : "+kettlebell1.equals(kettlebell2));
        System.out.println("====================================================================");

        Keyboard keyboard1 = new Keyboard("Logitech", "MX Keys", "Wireless");
        System.out.println(keyboard1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(keyboard1));
        System.out.println("Default Hash Code: " + keyboard1.hashCode());
        System.out.println("====================================================================");
        Keyboard keyboard2 = new Keyboard("Keychron", "K2", "Mechanical");
        System.out.println(keyboard2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(keyboard2));
        System.out.println("Default Hash Code: " + keyboard2.hashCode());
        System.out.println("Is Two instances same ? : "+keyboard1.equals(keyboard2));
        System.out.println("====================================================================");

        Kayak kayak1 = new Kayak("Pelican", "Mirage", 10);
        System.out.println(kayak1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kayak1));
        System.out.println("Default Hash Code: " + kayak1.hashCode());
        System.out.println("====================================================================");
        Kayak kayak2 = new Kayak("Old Town", "Dirigo", 12);
        System.out.println(kayak2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kayak2));
        System.out.println("Default Hash Code: " + kayak2.hashCode());
        System.out.println("Is Two instances same ? : "+kayak1.equals(kayak2));
        System.out.println("====================================================================");

        LegoSet lego1 = new LegoSet("Star Wars", "Millennium Falcon", 7541);
        System.out.println(lego1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(lego1));
        System.out.println("Default Hash Code: " + lego1.hashCode());
        System.out.println("====================================================================");
        LegoSet lego2 = new LegoSet("Technic", "Porsche 911", 42096);
        System.out.println(lego2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(lego2));
        System.out.println("Default Hash Code: " + lego2.hashCode());
        System.out.println("Is Two instances same ? : "+lego1.equals(lego2));
        System.out.println("====================================================================");

        MassageGun massageGun1 = new MassageGun("Theragun", "Prime", 5);
        System.out.println(massageGun1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(massageGun1));
        System.out.println("Default Hash Code: " + massageGun1.hashCode());
        System.out.println("====================================================================");
        MassageGun massageGun2 = new MassageGun("Hyperice", "Hypervolt", 4);
        System.out.println(massageGun2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(massageGun2));
        System.out.println("Default Hash Code: " + massageGun2.hashCode());
        System.out.println("Is Two instances same ? : "+massageGun1.equals(massageGun2));
        System.out.println("====================================================================");

        Microphone microphone1 = new Microphone("Blue", "Yeti", "USB");
        System.out.println(microphone1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(microphone1));
        System.out.println("Default Hash Code: " + microphone1.hashCode());
        System.out.println("====================================================================");
        Microphone microphone2 = new Microphone("Shure", "SM7B", "XLR");
        System.out.println(microphone2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(microphone2));
        System.out.println("Default Hash Code: " + microphone2.hashCode());
        System.out.println("Is Two instances same ? : "+microphone1.equals(microphone2));
        System.out.println("====================================================================");

        Notebook notebook1 = new Notebook("Moleskine", "Classic", 240);
        System.out.println(notebook1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(notebook1));
        System.out.println("Default Hash Code: " + notebook1.hashCode());
        System.out.println("====================================================================");
        Notebook notebook2 = new Notebook("Leuchtturm1917", "Medium", 249);
        System.out.println(notebook2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(notebook2));
        System.out.println("Default Hash Code: " + notebook2.hashCode());
        System.out.println("Is Two instances same ? : "+notebook1.equals(notebook2));
        System.out.println("====================================================================");

        OfficeChair chair1 = new OfficeChair("Herman Miller", "Aeron", "Mesh");
        System.out.println(chair1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(chair1));
        System.out.println("Default Hash Code: " + chair1.hashCode());
        System.out.println("====================================================================");
        OfficeChair chair2 = new OfficeChair("Steelcase", "Gesture", "Leather");
        System.out.println(chair2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(chair2));
        System.out.println("Default Hash Code: " + chair2.hashCode());
        System.out.println("Is Two instances same ? : "+chair1.equals(chair2));
        System.out.println("====================================================================");

        PaddleBoard paddleBoard1 = new PaddleBoard("iROCKER", "Cruiser", 11);
        System.out.println(paddleBoard1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(paddleBoard1));
        System.out.println("Default Hash Code: " + paddleBoard1.hashCode());
        System.out.println("====================================================================");
        PaddleBoard paddleBoard2 = new PaddleBoard("BOTE", "Aero", 10);
        System.out.println(paddleBoard2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(paddleBoard2));
        System.out.println("Default Hash Code: " + paddleBoard2.hashCode());
        System.out.println("Is Two instances same ? : "+paddleBoard1.equals(paddleBoard2));
        System.out.println("====================================================================");

        PaperShredder shredder1 = new PaperShredder("Fellowes", "62MC", 12);
        System.out.println(shredder1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(shredder1));
        System.out.println("Default Hash Code: " + shredder1.hashCode());
        System.out.println("====================================================================");
        PaperShredder shredder2 = new PaperShredder("Fellowes", "62MC", 12);
        System.out.println(shredder2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(shredder2));
        System.out.println("Default Hash Code: " + shredder2.hashCode());
        System.out.println("Is Two instances same ? : "+shredder1.equals(shredder2));
        System.out.println("====================================================================");

        Plant plant1 = new Plant("Monstera", "Deliciosa", "Indoor");
        System.out.println(plant1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(plant1));
        System.out.println("Default Hash Code: " + plant1.hashCode());
        System.out.println("====================================================================");
        Plant plant2 = new Plant("Monstera", "Deliciosa", "Indoor");
        System.out.println(plant2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(plant2));
        System.out.println("Default Hash Code: " + plant2.hashCode());
        System.out.println("Is Two instances same ? : "+plant1.equals(plant2));
        System.out.println("====================================================================");

        Printer printer1 = new Printer("HP", "OfficeJet", "Inkjet");
        System.out.println(printer1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(printer1));
        System.out.println("Default Hash Code: " + printer1.hashCode());
        System.out.println("====================================================================");
        Printer printer2 = new Printer("Brother", "HL-L2350DW", "Laser");
        System.out.println(printer2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(printer2));
        System.out.println("Default Hash Code: " + printer2.hashCode());
        System.out.println("Is Two instances same ? : "+printer1.equals(printer2));
        System.out.println("====================================================================");

        Projector projector1 = new Projector("Epson", "Home Cinema", 4000);
        System.out.println(projector1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(projector1));
        System.out.println("Default Hash Code: " + projector1.hashCode());
        System.out.println("====================================================================");
        Projector projector2 = new Projector("Epson", "Home Cinema", 4000);
        System.out.println(projector2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(projector2));
        System.out.println("Default Hash Code: " + projector2.hashCode());
        System.out.println("Is Two instances same ? : "+projector1.equals(projector2));
        System.out.println("====================================================================");

        PunchingBag punchingBag1 = new PunchingBag("Everlast", "PowerCore", 70);
        System.out.println(punchingBag1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(punchingBag1));
        System.out.println("Default Hash Code: " + punchingBag1.hashCode());
        System.out.println("====================================================================");

        PunchingBag punchingBag2 = new PunchingBag("Everlast", "PowerCore", 70);
        System.out.println(punchingBag2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(punchingBag2));
        System.out.println("Default Hash Code: " + punchingBag2.hashCode());
        System.out.println("Are the two PunchingBag instances equal? : " + punchingBag1.equals(punchingBag2));
        System.out.println("====================================================================");

        PunchingGloves gloves1 = new PunchingGloves("Everlast", "Pro Style", 16);
        System.out.println(gloves1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(gloves1));
        System.out.println("Default Hash Code: " + gloves1.hashCode());
        System.out.println("====================================================================");

        PunchingGloves gloves2 = new PunchingGloves("Everlast", "Pro Style", 16);
        System.out.println(gloves2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(gloves2));
        System.out.println("Default Hash Code: " + gloves2.hashCode());
        System.out.println("Are the two PunchingGloves instances equal? : " + gloves1.equals(gloves2));
        System.out.println("====================================================================");

        Puzzle puzzle1 = new Puzzle("Ravensburger", "Disney", 1000);
        System.out.println(puzzle1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(puzzle1));
        System.out.println("Default Hash Code: " + puzzle1.hashCode());
        System.out.println("====================================================================");

        Puzzle puzzle2 = new Puzzle("Ravensburger", "Disney", 1000);
        System.out.println(puzzle2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(puzzle2));
        System.out.println("Default Hash Code: " + puzzle2.hashCode());
        System.out.println("Are the two Puzzle instances equal? : " + puzzle1.equals(puzzle2));
        System.out.println("====================================================================");

        RCcar rcCar1 = new RCcar("Traxxas", "X-Maxx", "Electric");
        System.out.println(rcCar1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(rcCar1));
        System.out.println("Default Hash Code: " + rcCar1.hashCode());
        System.out.println("====================================================================");

        RCcar rcCar2 = new RCcar("Traxxas", "X-Maxx", "Electric");
        System.out.println(rcCar2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(rcCar2));
        System.out.println("Default Hash Code: " + rcCar2.hashCode());
        System.out.println("Are the two RCcar instances equal? : " + rcCar1.equals(rcCar2));
        System.out.println("====================================================================");

        ResistanceBands bands1 = new ResistanceBands("TheraBand", "Professional", 5);
        System.out.println(bands1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bands1));
        System.out.println("Default Hash Code: " + bands1.hashCode());
        System.out.println("====================================================================");

        ResistanceBands bands2 = new ResistanceBands("TheraBand", "Professional", 5);
        System.out.println(bands2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bands2));
        System.out.println("Default Hash Code: " + bands2.hashCode());
        System.out.println("Are the two ResistanceBands instances equal? : " + bands1.equals(bands2));
        System.out.println("====================================================================");

        RiceCooker riceCooker1 = new RiceCooker("Zojirushi", "NS-ZCC10", 5.5);
        System.out.println(riceCooker1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(riceCooker1));
        System.out.println("Default Hash Code: " + riceCooker1.hashCode());
        System.out.println("====================================================================");

        RiceCooker riceCooker2 = new RiceCooker("Zojirushi", "NS-ZCC10", 5.5);
        System.out.println(riceCooker2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(riceCooker2));
        System.out.println("Default Hash Code: " + riceCooker2.hashCode());
        System.out.println("Are the two RiceCooker instances equal? : " + riceCooker1.equals(riceCooker2));
        System.out.println("====================================================================");

        Router router1 = new Router("TP-Link", "Archer AX50", "Wi-Fi 6");
        System.out.println(router1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(router1));
        System.out.println("Default Hash Code: " + router1.hashCode());
        System.out.println("====================================================================");

        Router router2 = new Router("TP-Link", "Archer AX50", "Wi-Fi 6");
        System.out.println(router2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(router2));
        System.out.println("Default Hash Code: " + router2.hashCode());
        System.out.println("Are the two Router instances equal? : " + router1.equals(router2));
        System.out.println("====================================================================");

        RowingMachine rower1 = new RowingMachine("Concept2", "Model D", "Air");
        System.out.println(rower1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(rower1));
        System.out.println("Default Hash Code: " + rower1.hashCode());
        System.out.println("====================================================================");

        RowingMachine rower2 = new RowingMachine("Hydrow", "Wave", "Magnetic");
        System.out.println(rower2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(rower2));
        System.out.println("Default Hash Code: " + rower2.hashCode());
        System.out.println("Equals Check: " + rower1.equals(rower2));
        System.out.println("====================================================================");

        Scanner scanner1 = new Scanner("Fujitsu", "ScanSnap", "Document");
        System.out.println(scanner1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(scanner1));
        System.out.println("Default Hash Code: " + scanner1.hashCode());
        System.out.println("====================================================================");

        Scanner scanner2 = new Scanner("Epson", "WorkForce", "Flatbed");
        System.out.println(scanner2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(scanner2));
        System.out.println("Default Hash Code: " + scanner2.hashCode());
        System.out.println("Equals Check: " + scanner1.equals(scanner2));
        System.out.println("====================================================================");

        SecurityCamera securityCamera1 = new SecurityCamera("Ring", "Stick Up Cam", 1080);
        System.out.println(securityCamera1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(securityCamera1));
        System.out.println("Default Hash Code: " + securityCamera1.hashCode());
        System.out.println("====================================================================");

        SecurityCamera securityCamera2 = new SecurityCamera("Arlo", "Pro 4", 2);
        System.out.println(securityCamera2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(securityCamera2));
        System.out.println("Default Hash Code: " + securityCamera2.hashCode());
        System.out.println("Equals Check: " + securityCamera1.equals(securityCamera2));
        System.out.println("====================================================================");

        Skateboard skateboard1 = new Skateboard("Element", "Pro", 8.0);
        System.out.println(skateboard1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(skateboard1));
        System.out.println("Default Hash Code: " + skateboard1.hashCode());
        System.out.println("====================================================================");

        Skateboard skateboard2 = new Skateboard("Santa Cruz", "Dot", 8.25);
        System.out.println(skateboard2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(skateboard2));
        System.out.println("Default Hash Code: " + skateboard2.hashCode());
        System.out.println("Equals Check: " + skateboard1.equals(skateboard2));
        System.out.println("====================================================================");

        SleepingBag sleepingBag1 = new SleepingBag("The North Face", "Furnace", 0);
        System.out.println(sleepingBag1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(sleepingBag1));
        System.out.println("Default Hash Code: " + sleepingBag1.hashCode());
        System.out.println("====================================================================");

        SleepingBag sleepingBag2 = new SleepingBag("REI", "Co-op", 15);
        System.out.println(sleepingBag2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(sleepingBag2));
        System.out.println("Default Hash Code: " + sleepingBag2.hashCode());
        System.out.println("Equals Check: " + sleepingBag1.equals(sleepingBag2));
        System.out.println("====================================================================");

        SlowCooker slowCooker1 = new SlowCooker("Crock-Pot", "SCCPVL610", 6);
        System.out.println(slowCooker1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(slowCooker1));
        System.out.println("Default Hash Code: " + slowCooker1.hashCode());
        System.out.println("====================================================================");

        SlowCooker slowCooker2 = new SlowCooker("Instant Pot", "Duo", 8);
        System.out.println(slowCooker2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(slowCooker2));
        System.out.println("Default Hash Code: " + slowCooker2.hashCode());
        System.out.println("Equals Check: " + slowCooker1.equals(slowCooker2));
        System.out.println("====================================================================");

        SmartLock smartLock1 = new SmartLock("August", "Wi-Fi Smart Lock", "Keyless");
        System.out.println(smartLock1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(smartLock1));
        System.out.println("Default Hash Code: " + smartLock1.hashCode());
        System.out.println("====================================================================");

        SmartLock smartLock2 = new SmartLock("Schlage", "Encode", "Touchscreen");
        System.out.println(smartLock2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(smartLock2));
        System.out.println("Default Hash Code: " + smartLock2.hashCode());
        System.out.println("Equals Check: " + smartLock1.equals(smartLock2));
        System.out.println("====================================================================");

        SmartSpeaker speaker1 = new SmartSpeaker("Amazon", "Echo Dot", "Alexa");
        System.out.println(speaker1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(speaker1));
        System.out.println("Default Hash Code: " + speaker1.hashCode());
        System.out.println("====================================================================");

        SmartSpeaker speaker2 = new SmartSpeaker("Google", "Nest Mini", "Assistant");
        System.out.println(speaker2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(speaker2));
        System.out.println("Default Hash Code: " + speaker2.hashCode());
        System.out.println("Equals Check: " + speaker1.equals(speaker2));
        System.out.println("====================================================================");

        SmartThermostat thermostat1 = new SmartThermostat("Nest", "Learning", "Wi-Fi");
        System.out.println(thermostat1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(thermostat1));
        System.out.println("Default Hash Code: " + thermostat1.hashCode());
        System.out.println("====================================================================");

        SmartThermostat thermostat2 = new SmartThermostat("Ecobee", "SmartThermostat", "Voice");
        System.out.println(thermostat2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(thermostat2));
        System.out.println("Default Hash Code: " + thermostat2.hashCode());
        System.out.println("Equals Check: " + thermostat1.equals(thermostat2));
        System.out.println("====================================================================");

        SoccerBall soccerBall1 = new SoccerBall("Adidas", "Conext21", 5);
        System.out.println(soccerBall1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(soccerBall1));
        System.out.println("Default Hash Code: " + soccerBall1.hashCode());
        System.out.println("====================================================================");

        SoccerBall soccerBall2 = new SoccerBall("Nike", "Premier", 4);
        System.out.println(soccerBall2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(soccerBall2));
        System.out.println("Default Hash Code: " + soccerBall2.hashCode());
        System.out.println("Equals Check: " + soccerBall1.equals(soccerBall2));
        System.out.println("====================================================================");

        Snowboard snowboard1 = new Snowboard("Burton", "Custom", 158);
        System.out.println(snowboard1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(snowboard1));
        System.out.println("Default Hash Code: " + snowboard1.hashCode());
        System.out.println("====================================================================");

        Snowboard snowboard2 = new Snowboard("Lib Tech", "Orca", 153);
        System.out.println(snowboard2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(snowboard2));
        System.out.println("Default Hash Code: " + snowboard2.hashCode());
        System.out.println("Equals Check: " + snowboard1.equals(snowboard2));
        System.out.println("====================================================================");

        StandMixer standMixer1 = new StandMixer("KitchenAid", "Artisan", 5);
        System.out.println(standMixer1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(standMixer1));
        System.out.println("Default Hash Code: " + standMixer1.hashCode());
        System.out.println("====================================================================");

        StandMixer standMixer2 = new StandMixer("Cuisinart", "SM-50", 5);
        System.out.println(standMixer2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(standMixer2));
        System.out.println("Default Hash Code: " + standMixer2.hashCode());
        System.out.println("Equals Check: " + standMixer1.equals(standMixer2));
        System.out.println("====================================================================");

        Stapler stapler1 = new Stapler("Swingline", "747", 210);
        System.out.println(stapler1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(stapler1));
        System.out.println("Default Hash Code: " + stapler1.hashCode());
        System.out.println("====================================================================");

        Stapler stapler2 = new Stapler("Bostitch", "Heavy Duty", 150);
        System.out.println(stapler2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(stapler2));
        System.out.println("Default Hash Code: " + stapler2.hashCode());
        System.out.println("Equals Check: " + stapler1.equals(stapler2));
        System.out.println("====================================================================");

        Straightener straightener1 = new Straightener("GHD", "Classic", 1);
        System.out.println(straightener1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(straightener1));
        System.out.println("Default Hash Code: " + straightener1.hashCode());
        System.out.println("====================================================================");

        Straightener straightener2 = new Straightener("Dyson", "Corrale", 1.25);
        System.out.println(straightener2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(straightener2));
        System.out.println("Default Hash Code: " + straightener2.hashCode());
        System.out.println("Equals Check: " + straightener1.equals(straightener2));
        System.out.println("====================================================================");

        Suitcase suitcase1 = new Suitcase("Samsonite", "Winfield", 28);
        System.out.println(suitcase1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(suitcase1));
        System.out.println("Default Hash Code: " + suitcase1.hashCode());
        System.out.println("====================================================================");
        Suitcase suitcase2 = new Suitcase("Travelpro", "Maxlite", 25);
        System.out.println(suitcase2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(suitcase2));
        System.out.println("Default Hash Code: " + suitcase2.hashCode());
        System.out.println("Equal to suitcase1? " + suitcase2.equals(suitcase1));
        System.out.println("====================================================================");

        Surfboard surfboard1 = new Surfboard("Channel Islands", "Flyer", 6.0);
        System.out.println(surfboard1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(surfboard1));
        System.out.println("Default Hash Code: " + surfboard1.hashCode());
        System.out.println("====================================================================");
        Surfboard surfboard2 = new Surfboard("Firewire", "Seaside", 5.8);
        System.out.println(surfboard2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(surfboard2));
        System.out.println("Default Hash Code: " + surfboard2.hashCode());
        System.out.println("Equal to surfboard1? " + surfboard2.equals(surfboard1));
        System.out.println("====================================================================");

        Telescope telescope1 = new Telescope("Celestron", "PowerSeeker", 127);
        System.out.println(telescope1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(telescope1));
        System.out.println("Default Hash Code: " + telescope1.hashCode());
        System.out.println("====================================================================");
        Telescope telescope2 = new Telescope("Orion", "SkyQuest", 203);
        System.out.println(telescope2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(telescope2));
        System.out.println("Default Hash Code: " + telescope2.hashCode());
        System.out.println("Equal to telescope1? " + telescope2.equals(telescope1));
        System.out.println("====================================================================");

        Tent tent1 = new Tent("REI", "Half Dome", 4);
        System.out.println(tent1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tent1));
        System.out.println("Default Hash Code: " + tent1.hashCode());
        System.out.println("====================================================================");
        Tent tent2 = new Tent("Big Agnes", "Copper Spur", 2);
        System.out.println(tent2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tent2));
        System.out.println("Default Hash Code: " + tent2.hashCode());
        System.out.println("Equal to tent1? " + tent2.equals(tent1));
        System.out.println("====================================================================");

        TennisRacket tennisRacket1 = new TennisRacket("Wilson", "Pro Staff", 98);
        System.out.println(tennisRacket1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tennisRacket1));
        System.out.println("Default Hash Code: " + tennisRacket1.hashCode());
        System.out.println("====================================================================");
        TennisRacket tennisRacket2 = new TennisRacket("Babolat", "Pure Drive", 100);
        System.out.println(tennisRacket2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tennisRacket2));
        System.out.println("Default Hash Code: " + tennisRacket2.hashCode());
        System.out.println("Equal to tennisRacket1? " + tennisRacket2.equals(tennisRacket1));
        System.out.println("====================================================================");

        Thermometer thermometer1 = new Thermometer("Braun", "No Touch", "Forehead");
        System.out.println(thermometer1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(thermometer1));
        System.out.println("Default Hash Code: " + thermometer1.hashCode());
        System.out.println("====================================================================");
        Thermometer thermometer2 = new Thermometer("iHealth", "PT3", "Ear");
        System.out.println(thermometer2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(thermometer2));
        System.out.println("Default Hash Code: " + thermometer2.hashCode());
        System.out.println("Equal to thermometer1? " + thermometer2.equals(thermometer1));
        System.out.println("====================================================================");

        Treadmill treadmill1 = new Treadmill("NordicTrack", "Commercial", 12);
        System.out.println(treadmill1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(treadmill1));
        System.out.println("Default Hash Code: " + treadmill1.hashCode());
        System.out.println("====================================================================");
        Treadmill treadmill2 = new Treadmill("ProForm", "Carbon T10", 10);
        System.out.println(treadmill2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(treadmill2));
        System.out.println("Default Hash Code: " + treadmill2.hashCode());
        System.out.println("Equal to treadmill1? " + treadmill2.equals(treadmill1));
        System.out.println("====================================================================");

        VacuumCleaner vacuum1 = new VacuumCleaner("Dyson", "V11", "Cordless");
        System.out.println(vacuum1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(vacuum1));
        System.out.println("Default Hash Code: " + vacuum1.hashCode());
        System.out.println("====================================================================");
        VacuumCleaner vacuum2 = new VacuumCleaner("Shark", "Navigator", "Upright");
        System.out.println(vacuum2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(vacuum2));
        System.out.println("Default Hash Code: " + vacuum2.hashCode());
        System.out.println("Equal to vacuum1? " + vacuum2.equals(vacuum1));
        System.out.println("====================================================================");

        VRHeadset vrHeadset1 = new VRHeadset("Oculus", "Quest 2", 128);
        System.out.println(vrHeadset1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(vrHeadset1));
        System.out.println("Default Hash Code: " + vrHeadset1.hashCode());
        System.out.println("====================================================================");
        VRHeadset vrHeadset2 = new VRHeadset("Valve", "Index", 144);
        System.out.println(vrHeadset2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(vrHeadset2));
        System.out.println("Default Hash Code: " + vrHeadset2.hashCode());
        System.out.println("Equal to vrHeadset1? " + vrHeadset2.equals(vrHeadset1));
        System.out.println("====================================================================");

        Wallet wallet1 = new Wallet("Bellroy", "Hide & Seek", 8);
        System.out.println(wallet1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(wallet1));
        System.out.println("Default Hash Code: " + wallet1.hashCode());
        System.out.println("====================================================================");
        Wallet wallet2 = new Wallet("Ridge", "Aluminum", 12);
        System.out.println(wallet2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(wallet2));
        System.out.println("Default Hash Code: " + wallet2.hashCode());
        System.out.println("Equal to wallet1? " + wallet2.equals(wallet1));
        System.out.println("====================================================================");

        Watch watch1 = new Watch("Rolex", "Submariner", "Automatic");
        System.out.println(watch1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(watch1));
        System.out.println("Default Hash Code: " + watch1.hashCode());
        System.out.println("====================================================================");
        Watch watch2 = new Watch("Omega", "Seamaster", "Chronometer");
        System.out.println(watch2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(watch2));
        System.out.println("Default Hash Code: " + watch2.hashCode());
        System.out.println("Equal to watch1? " + watch2.equals(watch1));
        System.out.println("====================================================================");

        WaterFlosser flosser1 = new WaterFlosser("Waterpik", "WP-660", 10);
        System.out.println(flosser1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(flosser1));
        System.out.println("Default Hash Code: " + flosser1.hashCode());
        System.out.println("====================================================================");
        WaterFlosser flosser2 = new WaterFlosser("Philips", "Sonicare", 8);
        System.out.println(flosser2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(flosser2));
        System.out.println("Default Hash Code: " + flosser2.hashCode());
        System.out.println("Equal to flosser1? " + flosser2.equals(flosser1));
        System.out.println("====================================================================");

        Webcam webcam1 = new Webcam("Logitech", "C920", 1080);
        System.out.println(webcam1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(webcam1));
        System.out.println("Default Hash Code: " + webcam1.hashCode());
        System.out.println("====================================================================");
        Webcam webcam2 = new Webcam("Razer", "Kiyo Pro", 1080);
        System.out.println(webcam2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(webcam2));
        System.out.println("Default Hash Code: " + webcam2.hashCode());
        System.out.println("Equals webcam1? " + webcam2.equals(webcam1));
        System.out.println("====================================================================");

        WeightBench bench1 = new WeightBench("Bowflex", "5.1S", "Adjustable");
        System.out.println(bench1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bench1));
        System.out.println("Default Hash Code: " + bench1.hashCode());
        System.out.println("====================================================================");
        WeightBench bench2 = new WeightBench("Rep Fitness", "AB-3000", "Flat");
        System.out.println(bench2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bench2));
        System.out.println("Default Hash Code: " + bench2.hashCode());
        System.out.println("Equals bench1? " + bench2.equals(bench1));
        System.out.println("====================================================================");

        Whiteboard whiteboard1 = new Whiteboard("U Brands", "Magnetic", 36);
        System.out.println(whiteboard1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(whiteboard1));
        System.out.println("Default Hash Code: " + whiteboard1.hashCode());
        System.out.println("====================================================================");
        Whiteboard whiteboard2 = new Whiteboard("Quartet", "Glass", 48);
        System.out.println(whiteboard2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(whiteboard2));
        System.out.println("Default Hash Code: " + whiteboard2.hashCode());
        System.out.println("Equals whiteboard1? " + whiteboard2.equals(whiteboard1));
        System.out.println("====================================================================");

        YogaBlock yogaBlock1 = new YogaBlock("Gaiam", "Premium", "Cork");
        System.out.println(yogaBlock1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(yogaBlock1));
        System.out.println("Default Hash Code: " + yogaBlock1.hashCode());
        System.out.println("====================================================================");
        YogaBlock yogaBlock2 = new YogaBlock("Manduka", "Recycled", "Foam");
        System.out.println(yogaBlock2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(yogaBlock2));
        System.out.println("Default Hash Code: " + yogaBlock2.hashCode());
        System.out.println("Equals yogaBlock1? " + yogaBlock2.equals(yogaBlock1));
        System.out.println("====================================================================");

        YogaMat yogaMat1 = new YogaMat("Lululemon", "The Reversible", 5);
        System.out.println(yogaMat1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(yogaMat1));
        System.out.println("Default Hash Code: " + yogaMat1.hashCode());
        System.out.println("====================================================================");
        YogaMat yogaMat2 = new YogaMat("Jade", "Harmony", 4);
        System.out.println(yogaMat2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(yogaMat2));
        System.out.println("Default Hash Code: " + yogaMat2.hashCode());
        System.out.println("Equals yogaMat1? " + yogaMat2.equals(yogaMat1));
        System.out.println("====================================================================");

        Toaster toaster1 = new Toaster("Cuisinart", "CPT-122", 2);
        System.out.println(toaster1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(toaster1));
        System.out.println("Default Hash Code: " + toaster1.hashCode());
        System.out.println("====================================================================");
        Toaster toaster2 = new Toaster("Breville", "BTA840XL", 4);
        System.out.println(toaster2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(toaster2));
        System.out.println("Default Hash Code: " + toaster2.hashCode());
        System.out.println("Equals toaster1? " + toaster2.equals(toaster1));
        System.out.println("====================================================================");

        Toothbrush toothbrush1 = new Toothbrush("Oral-B", "iO Series 9", "Sonic");
        System.out.println(toothbrush1);
        System.out.println("Generated Hash Code: " + System.identityHashCode(toothbrush1));
        System.out.println("Default Hash Code: " + toothbrush1.hashCode());
        System.out.println("====================================================================");
        Toothbrush toothbrush2 = new Toothbrush("Philips", "Sonicare", "Electric");
        System.out.println(toothbrush2);
        System.out.println("Generated Hash Code: " + System.identityHashCode(toothbrush2));
        System.out.println("Default Hash Code: " + toothbrush2.hashCode());
        System.out.println("Equals toothbrush1? " + toothbrush2.equals(toothbrush1));
        System.out.println("====================================================================");

    }
}