package com.xworkz.overrideToString.runner;

import com.xworkz.overrideToString.internal.*;

public class Runner {
    public static void main(String[] args) {
        CoffeeMaker coffeeMaker = new CoffeeMaker("Keurig", "K-Elite", 12);
        System.out.println(coffeeMaker);
        System.out.println("Generated Hash Code: " + System.identityHashCode(coffeeMaker));
        System.out.println("Default Hash Code: " + coffeeMaker.hashCode());
        System.out.println("====================================================================");
        Guitar guitar = new Guitar("Fender", "Stratocaster", 6);
        System.out.println(guitar);
        System.out.println("Generated Hash Code: " + System.identityHashCode(guitar));
        System.out.println("Default Hash Code: " + guitar.hashCode());
        System.out.println("====================================================================");
        Skateboard skateboard = new Skateboard("Element", "Pro", 8.0);
        System.out.println(skateboard);
        System.out.println("Generated Hash Code: " + System.identityHashCode(skateboard));
        System.out.println("Default Hash Code: " + skateboard.hashCode());
        System.out.println("====================================================================");
        Drone drone = new Drone("DJI", "Mavic 3", 4);
        System.out.println(drone);
        System.out.println("Generated Hash Code: " + System.identityHashCode(drone));
        System.out.println("Default Hash Code: " + drone.hashCode());
        System.out.println("====================================================================");
        Headphones headphones = new Headphones("Sony", "WH-1000XM5", true);
        System.out.println(headphones);
        System.out.println("Generated Hash Code: " + System.identityHashCode(headphones));
        System.out.println("Default Hash Code: " + headphones.hashCode());
        System.out.println("====================================================================");
        Backpack backpack = new Backpack("North Face", "Borealis", 28);
        System.out.println(backpack);
        System.out.println("Generated Hash Code: " + System.identityHashCode(backpack));
        System.out.println("Default Hash Code: " + backpack.hashCode());
        System.out.println("====================================================================");
        Watch watch = new Watch("Rolex", "Submariner", "Automatic");
        System.out.println(watch);
        System.out.println("Generated Hash Code: " + System.identityHashCode(watch));
        System.out.println("Default Hash Code: " + watch.hashCode());
        System.out.println("====================================================================");
        Camera camera = new Camera("Canon", "EOS R5", 45);
        System.out.println(camera);
        System.out.println("Generated Hash Code: " + System.identityHashCode(camera));
        System.out.println("Default Hash Code: " + camera.hashCode());
        System.out.println("====================================================================");
        Plant plant = new Plant("Monstera", "Deliciosa", "Indoor");
        System.out.println(plant);
        System.out.println("Generated Hash Code: " + System.identityHashCode(plant));
        System.out.println("Default Hash Code: " + plant.hashCode());
        System.out.println("====================================================================");
        Basketball basketball = new Basketball("Spalding", "NBA Official", 29.5);
        System.out.println(basketball);
        System.out.println("Generated Hash Code: " + System.identityHashCode(basketball));
        System.out.println("Default Hash Code: " + basketball.hashCode());
        System.out.println("====================================================================");
        Tent tent = new Tent("REI", "Half Dome", 4);
        System.out.println(tent);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tent));
        System.out.println("Default Hash Code: " + tent.hashCode());
        System.out.println("====================================================================");
        SleepingBag sleepingBag = new SleepingBag("The North Face", "Furnace", 0);
        System.out.println(sleepingBag);
        System.out.println("Generated Hash Code: " + System.identityHashCode(sleepingBag));
        System.out.println("Default Hash Code: " + sleepingBag.hashCode());
        System.out.println("====================================================================");
        FishingRod fishingRod = new FishingRod("Shimano", "Stella", 7);
        System.out.println(fishingRod);
        System.out.println("Generated Hash Code: " + System.identityHashCode(fishingRod));
        System.out.println("Default Hash Code: " + fishingRod.hashCode());
        System.out.println("====================================================================");
        Dumbbell dumbbell = new Dumbbell("Bowflex", "SelectTech", 50);
        System.out.println(dumbbell);
        System.out.println("Generated Hash Code: " + System.identityHashCode(dumbbell));
        System.out.println("Default Hash Code: " + dumbbell.hashCode());
        System.out.println("====================================================================");
        YogaMat yogaMat = new YogaMat("Lululemon", "The Reversible", 5);
        System.out.println(yogaMat);
        System.out.println("Generated Hash Code: " + System.identityHashCode(yogaMat));
        System.out.println("Default Hash Code: " + yogaMat.hashCode());
        System.out.println("====================================================================");
        Surfboard surfboard = new Surfboard("Channel Islands", "Flyer", 6.0);
        System.out.println(surfboard);
        System.out.println("Generated Hash Code: " + System.identityHashCode(surfboard));
        System.out.println("Default Hash Code: " + surfboard.hashCode());
        System.out.println("====================================================================");
        Snowboard snowboard = new Snowboard("Burton", "Custom", 158);
        System.out.println(snowboard);
        System.out.println("Generated Hash Code: " + System.identityHashCode(snowboard));
        System.out.println("Default Hash Code: " + snowboard.hashCode());
        System.out.println("====================================================================");
        TennisRacket tennisRacket = new TennisRacket("Wilson", "Pro Staff", 98);
        System.out.println(tennisRacket);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tennisRacket));
        System.out.println("Default Hash Code: " + tennisRacket.hashCode());
        System.out.println("====================================================================");
        SoccerBall soccerBall = new SoccerBall("Adidas", "Conext21", 5);
        System.out.println(soccerBall);
        System.out.println("Generated Hash Code: " + System.identityHashCode(soccerBall));
        System.out.println("Default Hash Code: " + soccerBall.hashCode());
        System.out.println("====================================================================");
        BaseballBat baseballBat = new BaseballBat("Louisville Slugger", "Meta", 34);
        System.out.println(baseballBat);
        System.out.println("Generated Hash Code: " + System.identityHashCode(baseballBat));
        System.out.println("Default Hash Code: " + baseballBat.hashCode());
        System.out.println("====================================================================");
        Blender blender = new Blender("Vitamix", "5200", 64);
        System.out.println(blender);
        System.out.println("Generated Hash Code: " + System.identityHashCode(blender));
        System.out.println("Default Hash Code: " + blender.hashCode());
        System.out.println("====================================================================");
        Toaster toaster = new Toaster("Cuisinart", "CPT-122", 2);
        System.out.println(toaster);
        System.out.println("Generated Hash Code: " + System.identityHashCode(toaster));
        System.out.println("Default Hash Code: " + toaster.hashCode());
        System.out.println("====================================================================");
        VacuumCleaner vacuum = new VacuumCleaner("Dyson", "V11", "Cordless");
        System.out.println(vacuum);
        System.out.println("Generated Hash Code: " + System.identityHashCode(vacuum));
        System.out.println("Default Hash Code: " + vacuum.hashCode());
        System.out.println("====================================================================");
        AirFryer airFryer = new AirFryer("Ninja", "AF101", 4);
        System.out.println(airFryer);
        System.out.println("Generated Hash Code: " + System.identityHashCode(airFryer));
        System.out.println("Default Hash Code: " + airFryer.hashCode());
        System.out.println("====================================================================");
        RiceCooker riceCooker = new RiceCooker("Zojirushi", "NS-ZCC10", 5.5);
        System.out.println(riceCooker);
        System.out.println("Generated Hash Code: " + System.identityHashCode(riceCooker));
        System.out.println("Default Hash Code: " + riceCooker.hashCode());
        System.out.println("====================================================================");
        ElectricKettle kettle = new ElectricKettle("Breville", "BKE820", 1.7);
        System.out.println(kettle);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kettle));
        System.out.println("Default Hash Code: " + kettle.hashCode());
        System.out.println("====================================================================");
        SlowCooker slowCooker = new SlowCooker("Crock-Pot", "SCCPVL610", 6);
        System.out.println(slowCooker);
        System.out.println("Generated Hash Code: " + System.identityHashCode(slowCooker));
        System.out.println("Default Hash Code: " + slowCooker.hashCode());
        System.out.println("====================================================================");
        FoodProcessor foodProcessor = new FoodProcessor("Cuisinart", "DFP-14BCNY", 14);
        System.out.println(foodProcessor);
        System.out.println("Generated Hash Code: " + System.identityHashCode(foodProcessor));
        System.out.println("Default Hash Code: " + foodProcessor.hashCode());
        System.out.println("====================================================================");
        StandMixer standMixer = new StandMixer("KitchenAid", "Artisan", 5);
        System.out.println(standMixer);
        System.out.println("Generated Hash Code: " + System.identityHashCode(standMixer));
        System.out.println("Default Hash Code: " + standMixer.hashCode());
        System.out.println("====================================================================");
        Juicer juicer = new Juicer("Omega", "NC900HDC", "Cold Press");
        System.out.println(juicer);
        System.out.println("Generated Hash Code: " + System.identityHashCode(juicer));
        System.out.println("Default Hash Code: " + juicer.hashCode());
        System.out.println("====================================================================");
        HairDryer hairDryer = new HairDryer("Dyson", "Supersonic", 1875);
        System.out.println(hairDryer);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hairDryer));
        System.out.println("Default Hash Code: " + hairDryer.hashCode());
        System.out.println("====================================================================");
        Straightener straightener = new Straightener("GHD", "Classic", 1);
        System.out.println(straightener);
        System.out.println("Generated Hash Code: " + System.identityHashCode(straightener));
        System.out.println("Default Hash Code: " + straightener.hashCode());
        System.out.println("====================================================================");
        CurlingIron curlingIron = new CurlingIron("BaByliss", "PRO Nano", 1.25);
        System.out.println(curlingIron);
        System.out.println("Generated Hash Code: " + System.identityHashCode(curlingIron));
        System.out.println("Default Hash Code: " + curlingIron.hashCode());
        System.out.println("====================================================================");
        ElectricShaver shaver = new ElectricShaver("Braun", "Series 9", "Foil");
        System.out.println(shaver);
        System.out.println("Generated Hash Code: " + System.identityHashCode(shaver));
        System.out.println("Default Hash Code: " + shaver.hashCode());
        System.out.println("====================================================================");
        Toothbrush toothbrush = new Toothbrush("Oral-B", "iO Series 9", "Sonic");
        System.out.println(toothbrush);
        System.out.println("Generated Hash Code: " + System.identityHashCode(toothbrush));
        System.out.println("Default Hash Code: " + toothbrush.hashCode());
        System.out.println("====================================================================");
        WaterFlosser flosser = new WaterFlosser("Waterpik", "WP-660", 10);
        System.out.println(flosser);
        System.out.println("Generated Hash Code: " + System.identityHashCode(flosser));
        System.out.println("Default Hash Code: " + flosser.hashCode());
        System.out.println("====================================================================");
        MassageGun massageGun = new MassageGun("Theragun", "Prime", 5);
        System.out.println(massageGun);
        System.out.println("Generated Hash Code: " + System.identityHashCode(massageGun));
        System.out.println("Default Hash Code: " + massageGun.hashCode());
        System.out.println("====================================================================");
        BloodPressureMonitor bpMonitor = new BloodPressureMonitor("Omron", "Silver", "Upper Arm");
        System.out.println(bpMonitor);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bpMonitor));
        System.out.println("Default Hash Code: " + bpMonitor.hashCode());
        System.out.println("====================================================================");
        Thermometer thermometer = new Thermometer("Braun", "No Touch", "Forehead");
        System.out.println(thermometer);
        System.out.println("Generated Hash Code: " + System.identityHashCode(thermometer));
        System.out.println("Default Hash Code: " + thermometer.hashCode());
        System.out.println("====================================================================");
        Humidifier humidifier = new Humidifier("Honeywell", "HEV685", 1.5);
        System.out.println(humidifier);
        System.out.println("Generated Hash Code: " + System.identityHashCode(humidifier));
        System.out.println("Default Hash Code: " + humidifier.hashCode());
        System.out.println("====================================================================");
        AirPurifier airPurifier = new AirPurifier("Dyson", "Pure Cool", 3);
        System.out.println(airPurifier);
        System.out.println("Generated Hash Code: " + System.identityHashCode(airPurifier));
        System.out.println("Default Hash Code: " + airPurifier.hashCode());
        System.out.println("====================================================================");
        Projector projector = new Projector("Epson", "Home Cinema", 4000);
        System.out.println(projector);
        System.out.println("Generated Hash Code: " + System.identityHashCode(projector));
        System.out.println("Default Hash Code: " + projector.hashCode());
        System.out.println("====================================================================");
        Printer printer = new Printer("HP", "OfficeJet", "Inkjet");
        System.out.println(printer);
        System.out.println("Generated Hash Code: " + System.identityHashCode(printer));
        System.out.println("Default Hash Code: " + printer.hashCode());
        System.out.println("====================================================================");
        Scanner scanner = new Scanner("Fujitsu", "ScanSnap", "Document");
        System.out.println(scanner);
        System.out.println("Generated Hash Code: " + System.identityHashCode(scanner));
        System.out.println("Default Hash Code: " + scanner.hashCode());
        System.out.println("====================================================================");
        ExternalHDD hdd = new ExternalHDD("WD", "My Passport", 2);
        System.out.println(hdd);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hdd));
        System.out.println("Default Hash Code: " + hdd.hashCode());
        System.out.println("====================================================================");
        FlashDrive flashDrive = new FlashDrive("SanDisk", "Ultra Fit", 128);
        System.out.println(flashDrive);
        System.out.println("Generated Hash Code: " + System.identityHashCode(flashDrive));
        System.out.println("Default Hash Code: " + flashDrive.hashCode());
        System.out.println("====================================================================");
        Router router = new Router("TP-Link", "Archer AX50", "Wi-Fi 6");
        System.out.println(router);
        System.out.println("Generated Hash Code: " + System.identityHashCode(router));
        System.out.println("Default Hash Code: " + router.hashCode());
        System.out.println("====================================================================");
        SmartSpeaker speaker = new SmartSpeaker("Amazon", "Echo Dot", "Alexa");
        System.out.println(speaker);
        System.out.println("Generated Hash Code: " + System.identityHashCode(speaker));
        System.out.println("Default Hash Code: " + speaker.hashCode());
        System.out.println("====================================================================");
        SmartLock smartLock = new SmartLock("August", "Wi-Fi Smart Lock", "Keyless");
        System.out.println(smartLock);
        System.out.println("Generated Hash Code: " + System.identityHashCode(smartLock));
        System.out.println("Default Hash Code: " + smartLock.hashCode());
        System.out.println("====================================================================");
        SmartThermostat thermostat = new SmartThermostat("Nest", "Learning", "Wi-Fi");
        System.out.println(thermostat);
        System.out.println("Generated Hash Code: " + System.identityHashCode(thermostat));
        System.out.println("Default Hash Code: " + thermostat.hashCode());
        System.out.println("====================================================================");
        SecurityCamera securityCamera = new SecurityCamera("Ring", "Stick Up Cam", 1080);
        System.out.println(securityCamera);
        System.out.println("Generated Hash Code: " + System.identityHashCode(securityCamera));
        System.out.println("Default Hash Code: " + securityCamera.hashCode());
        System.out.println("====================================================================");
        ElectricScooter scooter = new ElectricScooter("Xiaomi", "Mi 365", 18.6);
        System.out.println(scooter);
        System.out.println("Generated Hash Code: " + System.identityHashCode(scooter));
        System.out.println("Default Hash Code: " + scooter.hashCode());
        System.out.println("====================================================================");
        ElectricBike eBike = new ElectricBike("Rad Power", "RadRover", 750);
        System.out.println(eBike);
        System.out.println("Generated Hash Code: " + System.identityHashCode(eBike));
        System.out.println("Default Hash Code: " + eBike.hashCode());
        System.out.println("====================================================================");
        Kayak kayak = new Kayak("Pelican", "Mirage", 10);
        System.out.println(kayak);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kayak));
        System.out.println("Default Hash Code: " + kayak.hashCode());
        System.out.println("====================================================================");
        PaddleBoard paddleBoard = new PaddleBoard("iROCKER", "Cruiser", 11);
        System.out.println(paddleBoard);
        System.out.println("Generated Hash Code: " + System.identityHashCode(paddleBoard));
        System.out.println("Default Hash Code: " + paddleBoard.hashCode());
        System.out.println("====================================================================");
        Binoculars binoculars = new Binoculars("Nikon", "Prostaff", 10);
        System.out.println(binoculars);
        System.out.println("Generated Hash Code: " + System.identityHashCode(binoculars));
        System.out.println("Default Hash Code: " + binoculars.hashCode());
        System.out.println("====================================================================");
        Telescope telescope = new Telescope("Celestron", "PowerSeeker", 127);
        System.out.println(telescope);
        System.out.println("Generated Hash Code: " + System.identityHashCode(telescope));
        System.out.println("Default Hash Code: " + telescope.hashCode());
        System.out.println("====================================================================");
        Hammock hammock = new Hammock("ENO", "DoubleNest", 400);
        System.out.println(hammock);
        System.out.println("Generated Hash Code: " + System.identityHashCode(hammock));
        System.out.println("Default Hash Code: " + hammock.hashCode());
        System.out.println("====================================================================");
        CampingStove stove = new CampingStove("Jetboil", "Flash", 1);
        System.out.println(stove);
        System.out.println("Generated Hash Code: " + System.identityHashCode(stove));
        System.out.println("Default Hash Code: " + stove.hashCode());
        System.out.println("====================================================================");
        Cooler cooler = new Cooler("Yeti", "Tundra", 65);
        System.out.println(cooler);
        System.out.println("Generated Hash Code: " + System.identityHashCode(cooler));
        System.out.println("Default Hash Code: " + cooler.hashCode());
        System.out.println("====================================================================");
        Suitcase suitcase = new Suitcase("Samsonite", "Winfield", 28);
        System.out.println(suitcase);
        System.out.println("Generated Hash Code: " + System.identityHashCode(suitcase));
        System.out.println("Default Hash Code: " + suitcase.hashCode());
        System.out.println("====================================================================");
        Briefcase briefcase = new Briefcase("Tumi", "Alpha", "Leather");
        System.out.println(briefcase);
        System.out.println("Generated Hash Code: " + System.identityHashCode(briefcase));
        System.out.println("Default Hash Code: " + briefcase.hashCode());
        System.out.println("====================================================================");
        Wallet wallet = new Wallet("Bellroy", "Hide & Seek", 8);
        System.out.println(wallet);
        System.out.println("Generated Hash Code: " + System.identityHashCode(wallet));
        System.out.println("Default Hash Code: " + wallet.hashCode());
        System.out.println("====================================================================");
        FountainPen pen = new FountainPen("Montblanc", "Meisterstück", "Gold");
        System.out.println(pen);
        System.out.println("Generated Hash Code: " + System.identityHashCode(pen));
        System.out.println("Default Hash Code: " + pen.hashCode());
        System.out.println("====================================================================");
        Notebook notebook = new Notebook("Moleskine", "Classic", 240);
        System.out.println(notebook);
        System.out.println("Generated Hash Code: " + System.identityHashCode(notebook));
        System.out.println("Default Hash Code: " + notebook.hashCode());
        System.out.println("====================================================================");
        DeskLamp lamp = new DeskLamp("TaoTronics", "LED Desk Lamp", "Adjustable");
        System.out.println(lamp);
        System.out.println("Generated Hash Code: " + System.identityHashCode(lamp));
        System.out.println("Default Hash Code: " + lamp.hashCode());
        System.out.println("====================================================================");
        OfficeChair chair = new OfficeChair("Herman Miller", "Aeron", "Mesh");
        System.out.println(chair);
        System.out.println("Generated Hash Code: " + System.identityHashCode(chair));
        System.out.println("Default Hash Code: " + chair.hashCode());
        System.out.println("====================================================================");
        Whiteboard whiteboard = new Whiteboard("U Brands", "Magnetic", 36);
        System.out.println(whiteboard);
        System.out.println("Generated Hash Code: " + System.identityHashCode(whiteboard));
        System.out.println("Default Hash Code: " + whiteboard.hashCode());
        System.out.println("====================================================================");
        Stapler stapler = new Stapler("Swingline", "747", 210);
        System.out.println(stapler);
        System.out.println("Generated Hash Code: " + System.identityHashCode(stapler));
        System.out.println("Default Hash Code: " + stapler.hashCode());
        System.out.println("====================================================================");
        PaperShredder shredder = new PaperShredder("Fellowes", "62MC", 12);
        System.out.println(shredder);
        System.out.println("Generated Hash Code: " + System.identityHashCode(shredder));
        System.out.println("Default Hash Code: " + shredder.hashCode());
        System.out.println("====================================================================");
        Calculator calculator = new Calculator("Texas Instruments", "TI-84", "Scientific");
        System.out.println(calculator);
        System.out.println("Generated Hash Code: " + System.identityHashCode(calculator));
        System.out.println("Default Hash Code: " + calculator.hashCode());
        System.out.println("====================================================================");
        Keyboard keyboard = new Keyboard("Logitech", "MX Keys", "Wireless");
        System.out.println(keyboard);
        System.out.println("Generated Hash Code: " + System.identityHashCode(keyboard));
        System.out.println("Default Hash Code: " + keyboard.hashCode());
        System.out.println("====================================================================");
        ComputerMouse mouse = new ComputerMouse("Razer", "DeathAdder", 20000);
        System.out.println(mouse);
        System.out.println("Generated Hash Code: " + System.identityHashCode(mouse));
        System.out.println("Default Hash Code: " + mouse.hashCode());
        System.out.println("====================================================================");
        Webcam webcam = new Webcam("Logitech", "C920", 1080);
        System.out.println(webcam);
        System.out.println("Generated Hash Code: " + System.identityHashCode(webcam));
        System.out.println("Default Hash Code: " + webcam.hashCode());
        System.out.println("====================================================================");
        Microphone microphone = new Microphone("Blue", "Yeti", "USB");
        System.out.println(microphone);
        System.out.println("Generated Hash Code: " + System.identityHashCode(microphone));
        System.out.println("Default Hash Code: " + microphone.hashCode());
        System.out.println("====================================================================");
        GraphicsTablet tablet = new GraphicsTablet("Wacom", "Intuos", "Medium");
        System.out.println(tablet);
        System.out.println("Generated Hash Code: " + System.identityHashCode(tablet));
        System.out.println("Default Hash Code: " + tablet.hashCode());
        System.out.println("====================================================================");
        GamingConsole console = new GamingConsole("Sony", "PlayStation 5", "Digital");
        System.out.println(console);
        System.out.println("Generated Hash Code: " + System.identityHashCode(console));
        System.out.println("Default Hash Code: " + console.hashCode());
        System.out.println("====================================================================");
        GamingController controller = new GamingController("Microsoft", "Xbox Elite", "Wireless");
        System.out.println(controller);
        System.out.println("Generated Hash Code: " + System.identityHashCode(controller));
        System.out.println("Default Hash Code: " + controller.hashCode());
        System.out.println("====================================================================");
        VRHeadset vrHeadset = new VRHeadset("Oculus", "Quest 2", 128);
        System.out.println(vrHeadset);
        System.out.println("Generated Hash Code: " + System.identityHashCode(vrHeadset));
        System.out.println("Default Hash Code: " + vrHeadset.hashCode());
        System.out.println("====================================================================");
        BoardGame boardGame = new BoardGame("Catan", "Strategy", 4);
        System.out.println(boardGame);
        System.out.println("Generated Hash Code: " + System.identityHashCode(boardGame));
        System.out.println("Default Hash Code: " + boardGame.hashCode());
        System.out.println("====================================================================");
        Puzzle puzzle = new Puzzle("Ravensburger", "Disney", 1000);
        System.out.println(puzzle);
        System.out.println("Generated Hash Code: " + System.identityHashCode(puzzle));
        System.out.println("Default Hash Code: " + puzzle.hashCode());
        System.out.println("====================================================================");
        LegoSet lego = new LegoSet("Star Wars", "Millennium Falcon", 7541);
        System.out.println(lego);
        System.out.println("Generated Hash Code: " + System.identityHashCode(lego));
        System.out.println("Default Hash Code: " + lego.hashCode());
        System.out.println("====================================================================");
        ActionFigure figure = new ActionFigure("Marvel", "Iron Man", 6);
        System.out.println(figure);
        System.out.println("Generated Hash Code: " + System.identityHashCode(figure));
        System.out.println("Default Hash Code: " + figure.hashCode());
        System.out.println("====================================================================");
        RCcar rcCar = new RCcar("Traxxas", "X-Maxx", "Electric");
        System.out.println(rcCar);
        System.out.println("Generated Hash Code: " + System.identityHashCode(rcCar));
        System.out.println("Default Hash Code: " + rcCar.hashCode());
        System.out.println("====================================================================");
        DroneRacingSet racingDrone = new DroneRacingSet("DJI", "FPV", 87);
        System.out.println(racingDrone);
        System.out.println("Generated Hash Code: " + System.identityHashCode(racingDrone));
        System.out.println("Default Hash Code: " + racingDrone.hashCode());
        System.out.println("====================================================================");
        FishingReel reel = new FishingReel("Shimano", "Stradic", 3000);
        System.out.println(reel);
        System.out.println("Generated Hash Code: " + System.identityHashCode(reel));
        System.out.println("Default Hash Code: " + reel.hashCode());
        System.out.println("====================================================================");
        GolfClub golfClub = new GolfClub("Callaway", "Mavrik", "Driver");
        System.out.println(golfClub);
        System.out.println("Generated Hash Code: " + System.identityHashCode(golfClub));
        System.out.println("Default Hash Code: " + golfClub.hashCode());
        System.out.println("====================================================================");
        DumbbellSet dumbbellSet = new DumbbellSet("Bowflex", "SelectTech", 52.5);
        System.out.println(dumbbellSet);
        System.out.println("Generated Hash Code: " + System.identityHashCode(dumbbellSet));
        System.out.println("Default Hash Code: " + dumbbellSet.hashCode());
        System.out.println("====================================================================");
        PunchingBag punchingBag = new PunchingBag("Everlast", "PowerCore", 70);
        System.out.println(punchingBag);
        System.out.println("Generated Hash Code: " + System.identityHashCode(punchingBag));
        System.out.println("Default Hash Code: " + punchingBag.hashCode());
        System.out.println("====================================================================");
        Treadmill treadmill = new Treadmill("NordicTrack", "Commercial", 12);
        System.out.println(treadmill);
        System.out.println("Generated Hash Code: " + System.identityHashCode(treadmill));
        System.out.println("Default Hash Code: " + treadmill.hashCode());
        System.out.println("====================================================================");
        Elliptical elliptical = new Elliptical("ProForm", "Carbon E7", 20);
        System.out.println(elliptical);
        System.out.println("Generated Hash Code: " + System.identityHashCode(elliptical));
        System.out.println("Default Hash Code: " + elliptical.hashCode());
        System.out.println("====================================================================");
        ExerciseBike exerciseBike = new ExerciseBike("Peloton", "Bike+", 21.5);
        System.out.println(exerciseBike);
        System.out.println("Generated Hash Code: " + System.identityHashCode(exerciseBike));
        System.out.println("Default Hash Code: " + exerciseBike.hashCode());
        System.out.println("====================================================================");
        RowingMachine rower = new RowingMachine("Concept2", "Model D", "Air");
        System.out.println(rower);
        System.out.println("Generated Hash Code: " + System.identityHashCode(rower));
        System.out.println("Default Hash Code: " + rower.hashCode());
        System.out.println("====================================================================");
        WeightBench bench = new WeightBench("Bowflex", "5.1S", "Adjustable");
        System.out.println(bench);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bench));
        System.out.println("Default Hash Code: " + bench.hashCode());
        System.out.println("====================================================================");
        ResistanceBands bands = new ResistanceBands("TheraBand", "Professional", 5);
        System.out.println(bands);
        System.out.println("Generated Hash Code: " + System.identityHashCode(bands));
        System.out.println("Default Hash Code: " + bands.hashCode());
        System.out.println("====================================================================");
        JumpRope jumpRope = new JumpRope("Crossrope", "Get Lean", "Weighted");
        System.out.println(jumpRope);
        System.out.println("Generated Hash Code: " + System.identityHashCode(jumpRope));
        System.out.println("Default Hash Code: " + jumpRope.hashCode());
        System.out.println("====================================================================");
        FoamRoller roller = new FoamRoller("TriggerPoint", "Grid", "High Density");
        System.out.println(roller);
        System.out.println("Generated Hash Code: " + System.identityHashCode(roller));
        System.out.println("Default Hash Code: " + roller.hashCode());
        System.out.println("====================================================================");
        YogaBlock yogaBlock = new YogaBlock("Gaiam", "Premium", "Cork");
        System.out.println(yogaBlock);
        System.out.println("Generated Hash Code: " + System.identityHashCode(yogaBlock));
        System.out.println("Default Hash Code: " + yogaBlock.hashCode());
        System.out.println("====================================================================");
        Kettlebell kettlebell = new Kettlebell("CAP", "Enamel Coated", 35);
        System.out.println(kettlebell);
        System.out.println("Generated Hash Code: " + System.identityHashCode(kettlebell));
        System.out.println("Default Hash Code: " + kettlebell.hashCode());
        System.out.println("====================================================================");
        PunchingGloves gloves = new PunchingGloves("Everlast", "Pro Style", 16);
        System.out.println(gloves);
        System.out.println("Generated Hash Code: " + System.identityHashCode(gloves));
        System.out.println("Default Hash Code: " + gloves.hashCode());
    }
}